on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:      
      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1
      
      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v4
        with:
            name: my-extension
            path: ${{ steps.package.outputs.packagePath }}
